### ISSUE TITLE
Design The Contact Us page

### ISSUE THREAD

**Issue by DhananjayThomble** [AiSenseLLP/online-exam-mern#6] opened 2023-10-17 13:06 UTC

**Comment by 05-yuvraj-singh** [comment] 2023-10-18 11:03
if the issue is open, kindly assign it to me (:

**Comment by Rahultota12** [comment] 2023-10-22 02:18
Solve The Issues #6

**Comment by Rahultota12** [comment] 2023-10-23 10:08
solve the issues #6 Design The Contact Us Page

**Closed by Rahultota12** 2023-10-23 10:08 UTC
